#!/bin/bash

function check_parameters {
    for parameter in "$@"; do
        if ! [[ "$parameter" =~ ^[1-6]+$ ]]; then
            echo "Error! All parameters must be integer numbers from 1 to 6"
            echo "Please try again!"
            exit 1
        fi
    done

    if [[ $1 == $2 || $3 == $4 ]]; then
        echo "Error! You should used different parameters for color back and text in names and values"
        echo "Please try again with different parameters"
        exit 1
    fi
}
