#!/bin/bash

dir=$1

total_files=$(find "$dir" -type f | wc -l)
conf_files=$(find "$dir" -type f -name "*.conf" | wc -l)
text_files=$(find "$dir" -type f -exec file {} \; | grep -c "text")
exe_files=$(find "$dir" -type f -executable | wc -l)
log_files=$(find "$dir" -type f -name "*.log" | wc -l)
arch_files=$(find "$dir" -type f \( -name "*.tar" -o -name "*.gz" -o -name "*.zip" -o -name "*.bz2" -o -name "*.xz" -o -name "*.7z" -o -name "*.tgz" -o -name "*.rar" \) | wc -l)
symb_link=$(find "$dir" -type l | wc -l)